on:
  release:
    types: [published]
name: Deploy plugin zip
jobs:
  build-and-upload:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Build zip file
        run: composer run createzip

      - name: Attach zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/*.zip
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
